### ISSUE TITLE
composite key를 이용한 방법

### ISSUE THREAD

**Issue by younho9** [Ajou-Team6/RiotOpenAPI-GetLeagueV4#21]
Composite key를 이용해 id를 만들면 (summonerName + queueType) 한 유저가 여러 성적 정보를 가지고 있어도 각각의 Object를 구분하는 것이 가능해서 SetOfLeagueEntryDTO class를 따로 만들지 않고도 구현이 가능하네요.

마찬가지로 만들어 봤고 DB에는 이렇게 저장되네요.

![image](https://user-images.githubusercontent.com/48426991/61429058-c397bf00-a95f-11e9-80de-61a0401b29f0.png)

**Comment by SiverPineValley** [comment]
두 방법 모두 좋은거 같습니다

**Comment by SiverPineValley** [comment]
merge 하셔도 될거 같아요
